aspire:  
  webdriver:
     scope: 
   
  console:
    enabled: false 
  
  
  dashboard:
    integration:
     enabled: true
     share-link-file-path: ./reports/share_link.txt
     host: 82.212.71.230
     port: 5070
     path: api
     protocol: http
     logLevel: FULL
     projectId: 12 
     summary-report-template: ./Summary_Report_Template.txt
      
  
      
  jbehave:
    meta-data:
    - +production 
    thread: 1
    story-time-out: 3000 
    rerun: 1 
    softassert: 
      enabled: true 
    stories:
      defaultloader:
        enabled: true   
        include: 
          #- stories/01-login/TC-001**.story
          #- stories/02-Profile/TC-001**.story
          - stories/**/**.story
          #- stories/04-Google Verification/TC-**.story
          #- stories/**/TC-001-PublicationsPage(AIP Advances)**.story
          #- stories/**/TC-006-PasswordValidation3.story
          #- stories/09-Search/TC-0001**.story
          
          
          
     
          
       
  screenshot:
    enabled: true
    only-on-failure: true
    filesaver:
      enabled: true
      folder-location: ./screenshots/

spring:
  output:
    ansi:
      enabled: always  
logging:
  level: 
    com:
      aspire: DEBUG
  file: application_zurqan.log  


endpoints:
  beans:
    sensitive: false
  shutdown:
    enabled: true
  env:
    sensitive: false
    
    
server:
  port: 0







   